import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import '../shared/styles/global.scss'
import { Header } from "@/widgets/header";
import { Footer } from "@/widgets/footer";

const roboto = Roboto({subsets:['latin'], weight: ['300', '400', '500', '700']});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Header/>
        {children}
        <Footer/>
        </body>
    </html>
  );
}
